name: Go

on:
  push:
    branches: [ master ]

env:
  TAG: ${{ github.sha }}
  CONTAINERREGISTRY: ${{ secrets.CONTAINERREGISTRY }}
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.0
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: build image
      run: |
        echo 'Building image'
        docker build  -t $CONTAINERREGISTRY/tsacodingchallengeapi:$TAG  .
